platform :ios, '16.0'

target 'SOSApp' do
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 5.8'

  # WebSocket
  pod 'Starscream', '~> 4.0'

  # Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'SOSAppTests' do
    inherit! :search_paths
    # Test-specific pods
  end

  target 'SOSAppUITests' do
    inherit! :search_paths
    # UI test-specific pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
