apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sos-app
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sos-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: sos-app/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: NODE_ENV
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-secret
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: USER_SERVICE_URL
            - name: EMERGENCY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: EMERGENCY_SERVICE_URL
            - name: LOCATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: LOCATION_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: NOTIFICATION_SERVICE_URL
            - name: COMMUNICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: COMMUNICATION_SERVICE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-hosts
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-hosts
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-password
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: CORS_ORIGINS
            - name: CIRCUIT_BREAKER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: CIRCUIT_BREAKER_ENABLED
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
