apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sos-app
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: sos-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sos-app/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: NODE_ENV
            - name: PORT
              value: "3002"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-hosts
                  key: POSTGRES_USER_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-hosts
                  key: POSTGRES_USER_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-secret
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: AUTH_SERVICE_URL
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: CORS_ORIGINS
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
